"""Export the loaded, editable .blend. Never invokes the generator or saves the source."""
import hashlib
import json
import sys
from pathlib import Path

import bpy

HERE = Path(__file__).resolve().parent


def export():
    source = Path(bpy.data.filepath)
    if not source.is_file():
        raise RuntimeError("Open pitcher.blend before exporting")
    source_hash = hashlib.sha256(source.read_bytes()).hexdigest()
    scene = bpy.context.scene
    saved_frame = scene.frame_current
    rig = bpy.data.objects["PitcherRig"]
    if scene.render.fps != 60 or scene.render.fps_base != 1:
        raise RuntimeError("S0 requires 60 fps / fps_base=1")
    markers = [m for m in scene.timeline_markers if m.name == "release"]
    if len(markers) != 1 or len(scene.timeline_markers) != 1:
        raise RuntimeError("Expected exactly one authoritative release marker")
    marker = markers[0]
    if not scene.frame_start < marker.frame < scene.frame_end:
        raise RuntimeError("Release must lie inside the clip")
    if rig.animation_data.action.name != "pitch_R":
        raise RuntimeError("Expected the single pitch_R action")
    scene.frame_set(marker.frame)
    grip = rig.matrix_world @ rig.pose.bones["grip"].matrix.translation
    samples = {}
    for frame in range(scene.frame_start, scene.frame_end+1):
        scene.frame_set(frame)
        dg=bpy.context.evaluated_depsgraph_get()
        mesh=bpy.data.objects["PitcherMesh"].evaluated_get(dg)
        evaluated=mesh.to_mesh()
        points=[list(mesh.matrix_world @ v.co) for v in evaluated.vertices]
        samples[str(frame)]={"grip_blender_m":list(rig.matrix_world @ rig.pose.bones["grip"].matrix.translation),
                             "vertices_blender_m":points}
        mesh.to_mesh_clear()
    scene.frame_set(scene.frame_start)
    bpy.ops.object.select_all(action="DESELECT")
    for obj in bpy.data.collections["PitcherAsset"].objects: obj.select_set(True)
    bpy.context.view_layer.objects.active=rig
    # Export skin mesh as a root; its armature modifier still identifies the skin.
    bpy.data.objects["PitcherMesh"].parent=None
    path=source.with_suffix(".glb")
    result=bpy.ops.export_scene.gltf(
        filepath=str(path),export_format="GLB",use_selection=True,
        export_yup=True,export_materials="NONE",export_vertex_color="NAME",
        export_vertex_color_name="Color",export_all_vertex_colors=False,
        export_active_vertex_color_when_no_material=True,
        export_normals=False,export_texcoords=False,export_tangents=False,
        export_animations=True,export_animation_mode="ACTIVE_ACTIONS",export_nla_strips_merged_animation_name="pitch_R",
        export_frame_range=True,export_frame_step=1,export_force_sampling=True,
        export_sampling_interpolation_fallback="LINEAR",export_anim_slide_to_zero=True,
        export_optimize_animation_size=False,export_skins=True,
        export_influence_nb=4,export_all_influences=False,export_def_bones=False,
        export_leaf_bone=False,export_morph=False,export_extras=False,
        export_cameras=False,export_lights=False,export_gpu_instances=False,
        export_draco_mesh_compression_enable=False)
    bpy.data.objects["PitcherMesh"].parent=rig
    scene.frame_set(saved_frame)
    if result != {"FINISHED"}: raise RuntimeError(result)
    if hashlib.sha256(source.read_bytes()).hexdigest()!=source_hash:
        raise RuntimeError("Export changed the authoring source")
    release_s=(marker.frame-scene.frame_start)/60
    placement=list(scene["placement_game_m"])
    metadata=f'''# Generated by export_sample.py from the .blend release marker. Do not hand-edit timing.
schema_version = 1
source = "{source.name}"
source_sha256 = "{source_hash}"
glb = "{path.name}"
glb_sha256 = "{hashlib.sha256(path.read_bytes()).hexdigest()}"
blender_version = "{bpy.app.version_string}"
blender_build = "{bpy.app.build_hash.decode()}"

[space]
units = "metres"
origin = "rear-foot ground reference"
placement_game_m = {placement}
runtime_scale = 1.0
glb_to_game = "(-x, y, z) + placement_game_m; reflect X once, reverse triangle winding"
blender_to_glb = "(x, z, -y); standard Blender glTF +Y-up export"
front_glb = "-Z"
right_hand_glb = "+X"
blockout_proportion_scale_m = {scene["blockout_proportion_scale_m"]}

[clip]
name = "pitch_R"
fps = 60
fps_base = 1.0
start_frame = {scene.frame_start}
end_frame = {scene.frame_end}
time_origin_s = 0.0
duration_s = {(scene.frame_end-scene.frame_start)/60}
playback_speed = 1.0
loop = false

[release]
marker = "release"
authoring_frame = {marker.frame}
time_s = {release_s}
tick_at_240_hz = {(marker.frame-scene.frame_start)*4}
grip_node = "grip"
grip_parent = "hand_R"
grip_meaning = "held ball centre, not hand joint"
'''
    if "contact_intervals" in scene:
        metadata += "\n[review]\nkey_poses = " + json.dumps(scene["key_poses"]) + "\n"
        for name, intervals in json.loads(scene["contact_intervals"]).items():
            for first, last in intervals:
                metadata += f'\n[[contacts]]\nbone = "{name}"\nstart_frame = {first}\nend_frame = {last}\n'
    source.with_suffix(".toml").write_text(metadata,encoding="utf-8",newline="\n")
    evidence=HERE.parents[2]/"build"/"pitcher-s01"
    # HERE = pawapuro/batting/pitcher; repository is parents[2].
    evidence.mkdir(parents=True,exist_ok=True)
    (evidence/"source-samples.json").write_text(json.dumps(samples),encoding="utf-8")
    print("S0_EXPORTED",path,"release",marker.frame,release_s,"grip_blender",list(grip))


if __name__=="__main__":
    export()
